src/wallet.cpp

Changing default confirm target for fee estimation from 1 to 2 due to : 
https://github.com/litecoin-project/litecoin/issues/211

changing default confirm target for fee estimation to 2

---

src/script/standard.h

Bitcoin Core 0.11 increased the `OP_RETURN` relay to 80 bytes.

Increase OP_ RETURN relay to 80 bytes

---

src/chainparams.cpp

This commit does the same as
bitcoin/bitcoin@a2b04ddfe6452e7d6274f4096bf3f2aee695a6d9.
Fix #240

build: fix newer boost build with c++11

---

qa/rpc-tests/p2p-compactblocks.py

Changed nVersion to BIP9_TOP_BITS to prevent the test hanging.

Litecoin: Fix p2p-compactblocks.py test hang

---

depends/packages/miniupnpc.mk
doc/build-osx.md
src/net.cpp
src/qt/bitcoingui.cpp

Fixes protobuf2.6 depreciated warning. Issue https://github.com/litecoin-project/litecoin/issues/291

Update protobuf dependancy plus add upstream 0.13 commits

---

src/qt/locale/bitcoin_he.ts

Litecoin name was mistranslated in Hebrew with a double L (It was "LLitecoin" - means "To Litecoin"). Only one occurrence needs to have the double L.

Fix Litecoin name translation in Hebrew

---

CONTRIBUTING.md

In this commit, all references to `Bitcoin` or `Bitcoin Core` are replaced with `Litecoin` and `Litecoin Core`, respectively.  
In addition, I added a copyright line for *The Litecoin Core Developers* and provided the rightful attribution to the original `Bitcoin Core` team as per their MIT license.

Change references from BTC Core to LTC Core

---

src/qt/bitcoinunits.cpp

Make denominations more user friendly with lites and photons

Litecoin: Rename mLTC/μLTC to lites/photons.

---

src/crypto/scrypt.cpp
src/crypto/scrypt.h

be32enc() andn le32dec() are already declared in /usr/include/sys/endian.h under freebsd 11

freebsd compilation fix

---

configure.ac
doc/README.md
doc/build-osx.md
src/crypto/scrypt.cpp
src/httpserver.cpp

Fixes: https://github.com/litecoin-project/litecoin/issues/463
Adds additional build instructions for macOS
Addresses: https://github.com/litecoin-project/litecoin/pull/465
Removes dead link of readme page
Addresses: https://github.com/litecoin-project/litecoin/pull/462
Renames threads to be in line with Litecoin branding
Minor configure change which shows whether scrypt sse2 is enabled/disabled and fixes a syntax error.

Litecoin: Basic changes for v0.16 release

---

src/qt/bitcoin.cpp

fix for upstream bitcoin qt5 openssl issue: https://github.com/bitcoin/bitcoin/pull/14403

qt: Revert "Force TLS1.0+ for SSL connections"

---

doc/release-process.md

Add variables for gbuild thread and memory limits.  Simplifies using custom values.

Litecoin: Make it easier to specify gbuild resource limits

---

src/qt/trafficgraphwidget.cpp

Add missing QPainterPath include
This is needed to compile with Qt 5.15.
(cherry picked from commit 79b0a69)
Fix from: bitcoin#19097

Add missing QPainterPath include

---

contrib/macdeploy/detached-sig-create.sh
doc/release-process.md

Based on upstream PR https://github.com/bitcoin/bitcoin/pull/18187
Apple now requires the prior notarisation of binaries distributed outside of the Mac App Store, including Litecoin Core.
The PR aims to fix incorrect codesign params, as now required for notarisation by Apple. 
This PR also includes additional documentation for the macOS codesigner to generate the codesign receipts used for signed Gitian builds.

build: macOS notarisation process

---

depends/packages/boost.mk

Pull requests without a rationale and clear improvement may be closed
immediately.
Please provide clear motivation for your patch and explain how it improves
Litecoin Core user experience or Litecoin Core developer experience
significantly.
Litecoin Core has a thorough review process and even the most trivial change
needs to pass a lot of eyes and requires non-zero or even substantial time
effort to review. There is a huge lack of active reviewers on the project, so
patches often sit for a long time.
---
See bitcoin@36c10b9 from https://github.com/bitcoin/bitcoin/pull/21662

Update Boost download URL due to mirror sunsetting

---

src/wallet/walletdb.cpp

This fixes issue #833.
The class `CHDChain` contains `static const` variables initialized in-line:
```
class CHDChain
{
. . .
static const int VERSION_HD_BASE        = 1;
static const int VERSION_HD_CHAIN_SPLIT = 2;
```
That is risky from an ODR perspective - if the variables are ODR-used, there will be ODR violations.
https://en.cppreference.com/w/cpp/language/static#Constant_static_members
> If a const non-inline (since C++17) static data member or a constexpr static data member (since C++11)(until C++17) is [odr-used](https://en.cppreference.com/w/cpp/language/definition#ODR-use), a definition at namespace scope is still required, but it cannot have an initializer. A definition may be provided even though redundant (since C++17).
This PR provides the missing definitions in the **.cpp** …

Fix undefined reference to `CHDChain::VERSION_HD_CHAIN_SPLIT'

---

doc/build-unix.md

Add libssl-dev which is required for Linux Compiling

Fix Broken Linux Compiling Dependancies Instruction

---

src/support/lockedpool.h
src/util/bip32.h
src/util/string.h

I could not compile the project with `--enable-wallet` because these includes in headers were missing. Maybe I was missing some flag that includes them automatically?
Anyway, I was lazy to make an issue about it. Take it or close it.

Add missing includes

---

src/rpc/mining.cpp

Just for allow getblocktemplate request when we use regtest node mode, discussin [here](https://github.com/litecoin-project/litecoin/issues/967)

rpc: allow getblocktemplate for test chains when unconnected or in IBD

---

src/wallet/rpcdump.cpp
src/wallet/scriptpubkeyman.h

Dump MWEB view keys (scan secret and spend pubkey) for use in e.g. BTCPayServer.

wallet, rpc: add MWEB view keys to dumpwallet

---

src/index/base.cpp

The problems I encountered:
I have done customization development in WriteBlock(block, pindex) and WriteBlock(block, pindex) maybe return false, where i restart the node and find that the transaction cannot be obtained through the transaction index
Here's why:
If run Commit() first, then WriteBlock(block, pindex), At this time, the transaction indexed of the block has been marked as successfully created, but if WriteBlock(block, pindex) fails to be run, the transaction index is not really created, and the transaction data will not be found out through the transaction index. so WriteBlock(block, pindex) must be executed first before committing () is executed.

Fixed an issue where transaction indexes of block could be lost,
